//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class AccesorioHabitacion : XPObject
    {
        AccesorioEquipamiento fAccesorio;
        [Association(@"AccesorioHabitacionReferencesAccesorioEquipamiento")]
        public AccesorioEquipamiento Accesorio
        {
            get { return fAccesorio; }
            set { SetPropertyValue<AccesorioEquipamiento>(nameof(Accesorio), ref fAccesorio, value); }
        }
        Habitacion fHabitacion;
        [Association(@"AccesorioHabitacionReferencesHabitacion")]
        public Habitacion Habitacion
        {
            get { return fHabitacion; }
            set { SetPropertyValue<Habitacion>(nameof(Habitacion), ref fHabitacion, value); }
        }
        string fCantidad;
        public string Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<string>(nameof(Cantidad), ref fCantidad, value); }
        }
    }

}
