//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class AnulacionCobro : XPObject
    {
        DateTime fFechaAnulado;
        public DateTime FechaAnulado
        {
            get { return fFechaAnulado; }
            set { SetPropertyValue<DateTime>(nameof(FechaAnulado), ref fFechaAnulado, value); }
        }
        Usuario fSolicitudUsuario;
        [Association(@"AnulacionCobroReferencesUsuario1")]
        public Usuario SolicitudUsuario
        {
            get { return fSolicitudUsuario; }
            set { SetPropertyValue<Usuario>(nameof(SolicitudUsuario), ref fSolicitudUsuario, value); }
        }
        DateTime fFechaSolicitado;
        public DateTime FechaSolicitado
        {
            get { return fFechaSolicitado; }
            set { SetPropertyValue<DateTime>(nameof(FechaSolicitado), ref fFechaSolicitado, value); }
        }
        Usuario fAnulacionUsuario;
        [Association(@"AnulacionCobroReferencesUsuario")]
        public Usuario AnulacionUsuario
        {
            get { return fAnulacionUsuario; }
            set { SetPropertyValue<Usuario>(nameof(AnulacionUsuario), ref fAnulacionUsuario, value); }
        }
        [Association(@"CobroPendienteReferencesAnulacionCobro")]
        public XPCollection<CobroPendiente> CobroPendientes { get { return GetCollection<CobroPendiente>(nameof(CobroPendientes)); } }
    }

}
