//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Articulo : XPObject
    {
        int fTipoServicio;
        public int TipoServicio
        {
            get { return fTipoServicio; }
            set { SetPropertyValue<int>(nameof(TipoServicio), ref fTipoServicio, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fCodigoInterno;
        public string CodigoInterno
        {
            get { return fCodigoInterno; }
            set { SetPropertyValue<string>(nameof(CodigoInterno), ref fCodigoInterno, value); }
        }
        string fUnidadMedidaBase;
        public string UnidadMedidaBase
        {
            get { return fUnidadMedidaBase; }
            set { SetPropertyValue<string>(nameof(UnidadMedidaBase), ref fUnidadMedidaBase, value); }
        }
        string fUnidadMedidaCompra;
        public string UnidadMedidaCompra
        {
            get { return fUnidadMedidaCompra; }
            set { SetPropertyValue<string>(nameof(UnidadMedidaCompra), ref fUnidadMedidaCompra, value); }
        }
        string fUnidadMedidaVenta;
        public string UnidadMedidaVenta
        {
            get { return fUnidadMedidaVenta; }
            set { SetPropertyValue<string>(nameof(UnidadMedidaVenta), ref fUnidadMedidaVenta, value); }
        }
        int fExistenciaMaxima;
        public int ExistenciaMaxima
        {
            get { return fExistenciaMaxima; }
            set { SetPropertyValue<int>(nameof(ExistenciaMaxima), ref fExistenciaMaxima, value); }
        }
        int fExistenciaMinima;
        public int ExistenciaMinima
        {
            get { return fExistenciaMinima; }
            set { SetPropertyValue<int>(nameof(ExistenciaMinima), ref fExistenciaMinima, value); }
        }
        double fPuntoReorden;
        public double PuntoReorden
        {
            get { return fPuntoReorden; }
            set { SetPropertyValue<double>(nameof(PuntoReorden), ref fPuntoReorden, value); }
        }
        bool fDisponiblePedido;
        public bool DisponiblePedido
        {
            get { return fDisponiblePedido; }
            set { SetPropertyValue<bool>(nameof(DisponiblePedido), ref fDisponiblePedido, value); }
        }
        bool fDisponibleVenta;
        public bool DisponibleVenta
        {
            get { return fDisponibleVenta; }
            set { SetPropertyValue<bool>(nameof(DisponibleVenta), ref fDisponibleVenta, value); }
        }
        bool fEsPerecedero;
        public bool EsPerecedero
        {
            get { return fEsPerecedero; }
            set { SetPropertyValue<bool>(nameof(EsPerecedero), ref fEsPerecedero, value); }
        }
        bool fInventariable;
        public bool Inventariable
        {
            get { return fInventariable; }
            set { SetPropertyValue<bool>(nameof(Inventariable), ref fInventariable, value); }
        }
        decimal fCostoActual;
        public decimal CostoActual
        {
            get { return fCostoActual; }
            set { SetPropertyValue<decimal>(nameof(CostoActual), ref fCostoActual, value); }
        }
        decimal fPrecioVenta;
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        decimal fPrecioCompra;
        public decimal PrecioCompra
        {
            get { return fPrecioCompra; }
            set { SetPropertyValue<decimal>(nameof(PrecioCompra), ref fPrecioCompra, value); }
        }
        CategoriaArticulo fCategoria;
        [Association(@"ArticuloReferencesCategoriaArticulo")]
        public CategoriaArticulo Categoria
        {
            get { return fCategoria; }
            set { SetPropertyValue<CategoriaArticulo>(nameof(Categoria), ref fCategoria, value); }
        }
        [Association(@"CobroPendienteReferencesArticulo")]
        public XPCollection<CobroPendiente> CobroPendientes { get { return GetCollection<CobroPendiente>(nameof(CobroPendientes)); } }
        [Association(@"UnidadMedidaReferencesArticulo")]
        public XPCollection<UnidadMedida> UnidadMedidas { get { return GetCollection<UnidadMedida>(nameof(UnidadMedidas)); } }
    }

}
