//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class AsignacionUsuarioLimpieza : XPObject
    {
        Usuario fUsuario;
        [Association(@"AsignacionUsuarioLimpiezaReferencesUsuario")]
        public Usuario Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<Usuario>(nameof(Usuario), ref fUsuario, value); }
        }
        Habitacion fHabitacion;
        [Association(@"AsignacionUsuarioLimpiezaReferencesHabitacion")]
        public Habitacion Habitacion
        {
            get { return fHabitacion; }
            set { SetPropertyValue<Habitacion>(nameof(Habitacion), ref fHabitacion, value); }
        }
        DateTime fFechaAsignacion;
        public DateTime FechaAsignacion
        {
            get { return fFechaAsignacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaAsignacion), ref fFechaAsignacion, value); }
        }
        DateTime fHoraFinalizacion;
        public DateTime HoraFinalizacion
        {
            get { return fHoraFinalizacion; }
            set { SetPropertyValue<DateTime>(nameof(HoraFinalizacion), ref fHoraFinalizacion, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
    }

}
