//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class CategoriaArticulo : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        CategoriaArticulo fParentesco;
        [Association(@"CategoriaArticuloReferencesCategoriaArticulo")]
        public CategoriaArticulo Parentesco
        {
            get { return fParentesco; }
            set { SetPropertyValue<CategoriaArticulo>(nameof(Parentesco), ref fParentesco, value); }
        }
        [Association(@"ArticuloReferencesCategoriaArticulo")]
        public XPCollection<Articulo> Articuloes { get { return GetCollection<Articulo>(nameof(Articuloes)); } }
        [Association(@"CategoriaArticuloReferencesCategoriaArticulo")]
        public XPCollection<CategoriaArticulo> CategoriaArticuloCollection { get { return GetCollection<CategoriaArticulo>(nameof(CategoriaArticuloCollection)); } }
    }

}
