//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(AccesorioEquipamiento),
            typeof(AccesorioHabitacion),
            typeof(AccesorioVehiculo),
            typeof(AnulacionCobro),
            typeof(Articulo),
            typeof(AsignacionUsuarioLimpieza),
            typeof(CategoriaArticulo),
            typeof(Ciudad),
            typeof(ClaseCliente),
            typeof(CobroPendiente),
            typeof(ComandasTurno),
            typeof(ComandasVendidasTurno),
            typeof(CorteDeCaja),
            typeof(CuentaServicios),
            typeof(DetalleCobros),
            typeof(DetallePago),
            typeof(DetalleVenta),
            typeof(Direccion),
            typeof(Empleado),
            typeof(Empresa),
            typeof(Entidad),
            typeof(Estado),
            typeof(EstadoHabitacion),
            typeof(FormaDePago),
            typeof(Habitacion),
            typeof(Hotel),
            typeof(Mueble),
            typeof(Pais),
            typeof(PreciosTarifas),
            typeof(PromocionHotel),
            typeof(RangoDocumento),
            typeof(RentaVehiculo),
            typeof(ReportDataV2),
            typeof(ReporteCxcEmpleado),
            typeof(ReporteTurnos),
            typeof(ReservacionHabitacion),
            typeof(ReservacionHotel),
            typeof(ReservacionTarifas),
            typeof(ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollection),
            typeof(ReservacionVehiculo),
            typeof(Roles),
            typeof(ServicioAdicional),
            typeof(ServicioExtraReservacionHotel),
            typeof(ServicioExtraVehiculo),
            typeof(ServiciosHabitaciones),
            typeof(Sesiones),
            typeof(Sucursal),
            typeof(TarifaHabitacion),
            typeof(TarifaPromocion),
            typeof(TarifasVehiculo),
            typeof(TarifaVehiculo),
            typeof(TipoDocumento),
            typeof(TipoHabitacion),
            typeof(TipoImpuesto),
            typeof(Transaccion),
            typeof(Turno),
            typeof(UnidadMedida),
            typeof(UnidadOrganizativa),
            typeof(Usuario),
            typeof(Vehiculo),
            typeof(VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollection),
            typeof(Venta)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings[".Business"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
