//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class CorteDeCaja : XPObject
    {
        Turno fTurno;
        [Association(@"CorteDeCajaReferencesTurno")]
        public Turno Turno
        {
            get { return fTurno; }
            set { SetPropertyValue<Turno>(nameof(Turno), ref fTurno, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        decimal fSaldoAnterior;
        public decimal SaldoAnterior
        {
            get { return fSaldoAnterior; }
            set { SetPropertyValue<decimal>(nameof(SaldoAnterior), ref fSaldoAnterior, value); }
        }
        decimal fIncrementoDeRubro;
        public decimal IncrementoDeRubro
        {
            get { return fIncrementoDeRubro; }
            set { SetPropertyValue<decimal>(nameof(IncrementoDeRubro), ref fIncrementoDeRubro, value); }
        }
        decimal fIngresoEfectivo;
        public decimal IngresoEfectivo
        {
            get { return fIngresoEfectivo; }
            set { SetPropertyValue<decimal>(nameof(IngresoEfectivo), ref fIngresoEfectivo, value); }
        }
        decimal fEgresos;
        public decimal Egresos
        {
            get { return fEgresos; }
            set { SetPropertyValue<decimal>(nameof(Egresos), ref fEgresos, value); }
        }
        decimal fSaldoActual;
        public decimal SaldoActual
        {
            get { return fSaldoActual; }
            set { SetPropertyValue<decimal>(nameof(SaldoActual), ref fSaldoActual, value); }
        }
        decimal fMontoTarjetaCredito;
        public decimal MontoTarjetaCredito
        {
            get { return fMontoTarjetaCredito; }
            set { SetPropertyValue<decimal>(nameof(MontoTarjetaCredito), ref fMontoTarjetaCredito, value); }
        }
        decimal fMontoCheque;
        public decimal MontoCheque
        {
            get { return fMontoCheque; }
            set { SetPropertyValue<decimal>(nameof(MontoCheque), ref fMontoCheque, value); }
        }
        decimal fMontoEnLinea;
        public decimal MontoEnLinea
        {
            get { return fMontoEnLinea; }
            set { SetPropertyValue<decimal>(nameof(MontoEnLinea), ref fMontoEnLinea, value); }
        }
        decimal fSubTotal;
        public decimal SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<decimal>(nameof(SubTotal), ref fSubTotal, value); }
        }
        decimal fNuevoSaldo;
        public decimal NuevoSaldo
        {
            get { return fNuevoSaldo; }
            set { SetPropertyValue<decimal>(nameof(NuevoSaldo), ref fNuevoSaldo, value); }
        }
        Sucursal fSucursal;
        [Association(@"CorteDeCajaReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        bool fFinalizado;
        public bool Finalizado
        {
            get { return fFinalizado; }
            set { SetPropertyValue<bool>(nameof(Finalizado), ref fFinalizado, value); }
        }
        bool fSolicitado;
        public bool Solicitado
        {
            get { return fSolicitado; }
            set { SetPropertyValue<bool>(nameof(Solicitado), ref fSolicitado, value); }
        }
        bool fReporteCobros;
        public bool ReporteCobros
        {
            get { return fReporteCobros; }
            set { SetPropertyValue<bool>(nameof(ReporteCobros), ref fReporteCobros, value); }
        }
        decimal fTotalDia;
        public decimal TotalDia
        {
            get { return fTotalDia; }
            set { SetPropertyValue<decimal>(nameof(TotalDia), ref fTotalDia, value); }
        }
        decimal fIngresoRestaurante;
        public decimal IngresoRestaurante
        {
            get { return fIngresoRestaurante; }
            set { SetPropertyValue<decimal>(nameof(IngresoRestaurante), ref fIngresoRestaurante, value); }
        }
        decimal fIngresoAgua;
        public decimal IngresoAgua
        {
            get { return fIngresoAgua; }
            set { SetPropertyValue<decimal>(nameof(IngresoAgua), ref fIngresoAgua, value); }
        }
        decimal fIngresoOtrosServicios;
        public decimal IngresoOtrosServicios
        {
            get { return fIngresoOtrosServicios; }
            set { SetPropertyValue<decimal>(nameof(IngresoOtrosServicios), ref fIngresoOtrosServicios, value); }
        }
        decimal fEfectivoAcumulado;
        public decimal EfectivoAcumulado
        {
            get { return fEfectivoAcumulado; }
            set { SetPropertyValue<decimal>(nameof(EfectivoAcumulado), ref fEfectivoAcumulado, value); }
        }
        decimal fMontoCredito;
        public decimal MontoCredito
        {
            get { return fMontoCredito; }
            set { SetPropertyValue<decimal>(nameof(MontoCredito), ref fMontoCredito, value); }
        }
        [Association(@"VentaReferencesCorteDeCaja")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
