//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class CuentaServicios : XPObject
    {
        string fConcepto;
        public string Concepto
        {
            get { return fConcepto; }
            set { SetPropertyValue<string>(nameof(Concepto), ref fConcepto, value); }
        }
        DateTime fFechaCreacion;
        public DateTime FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        DateTime fFechaCierre;
        public DateTime FechaCierre
        {
            get { return fFechaCierre; }
            set { SetPropertyValue<DateTime>(nameof(FechaCierre), ref fFechaCierre, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        decimal fSaldo;
        public decimal Saldo
        {
            get { return fSaldo; }
            set { SetPropertyValue<decimal>(nameof(Saldo), ref fSaldo, value); }
        }
        Entidad fCliente;
        [Association(@"CuentaServiciosReferencesEntidad")]
        public Entidad Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Entidad>(nameof(Cliente), ref fCliente, value); }
        }
        bool fBoolCliente;
        public bool BoolCliente
        {
            get { return fBoolCliente; }
            set { SetPropertyValue<bool>(nameof(BoolCliente), ref fBoolCliente, value); }
        }
        Empleado fEmpleado;
        [Association(@"CuentaServiciosReferencesEmpleado")]
        public Empleado Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(Empleado), ref fEmpleado, value); }
        }
        [Association(@"DetalleCobrosReferencesCuentaServicios")]
        public XPCollection<DetalleCobros> DetalleCobrosCollection { get { return GetCollection<DetalleCobros>(nameof(DetalleCobrosCollection)); } }
        [Association(@"RentaVehiculoReferencesCuentaServicios")]
        public XPCollection<RentaVehiculo> RentaVehiculoes { get { return GetCollection<RentaVehiculo>(nameof(RentaVehiculoes)); } }
        [Association(@"ReservacionHotelReferencesCuentaServicios")]
        public XPCollection<ReservacionHotel> ReservacionHotels { get { return GetCollection<ReservacionHotel>(nameof(ReservacionHotels)); } }
        [Association(@"VentaReferencesCuentaServicios")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
