//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class DetalleCobros : XPObject
    {
        DateTime fFechaCreacion;
        public DateTime FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        CuentaServicios fCobro;
        [Association(@"DetalleCobrosReferencesCuentaServicios")]
        public CuentaServicios Cobro
        {
            get { return fCobro; }
            set { SetPropertyValue<CuentaServicios>(nameof(Cobro), ref fCobro, value); }
        }
        decimal fPrecioUnitario;
        public decimal PrecioUnitario
        {
            get { return fPrecioUnitario; }
            set { SetPropertyValue<decimal>(nameof(PrecioUnitario), ref fPrecioUnitario, value); }
        }
        double fDescuento;
        public double Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<double>(nameof(Descuento), ref fDescuento, value); }
        }
        int fTipoServicio;
        public int TipoServicio
        {
            get { return fTipoServicio; }
            set { SetPropertyValue<int>(nameof(TipoServicio), ref fTipoServicio, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        Empleado fEmpleado;
        [Association(@"DetalleCobrosReferencesEmpleado")]
        public Empleado Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(Empleado), ref fEmpleado, value); }
        }
        Entidad fCliente;
        [Association(@"DetalleCobrosReferencesEntidad")]
        public Entidad Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Entidad>(nameof(Cliente), ref fCliente, value); }
        }
        bool fBoolCliente;
        public bool BoolCliente
        {
            get { return fBoolCliente; }
            set { SetPropertyValue<bool>(nameof(BoolCliente), ref fBoolCliente, value); }
        }
        Sucursal fSucursal;
        [Association(@"DetalleCobrosReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        decimal fPrecioUnitarioConIva;
        public decimal PrecioUnitarioConIva
        {
            get { return fPrecioUnitarioConIva; }
            set { SetPropertyValue<decimal>(nameof(PrecioUnitarioConIva), ref fPrecioUnitarioConIva, value); }
        }
        decimal fPrecioUnitarioSinIva;
        public decimal PrecioUnitarioSinIva
        {
            get { return fPrecioUnitarioSinIva; }
            set { SetPropertyValue<decimal>(nameof(PrecioUnitarioSinIva), ref fPrecioUnitarioSinIva, value); }
        }
        [Association(@"DetalleVentaReferencesDetalleCobros")]
        public XPCollection<DetalleVenta> DetalleVentas { get { return GetCollection<DetalleVenta>(nameof(DetalleVentas)); } }
        [Association(@"ServicioExtraVehiculoReferencesDetalleCobros")]
        public XPCollection<ServicioExtraVehiculo> ServicioExtraVehiculoes { get { return GetCollection<ServicioExtraVehiculo>(nameof(ServicioExtraVehiculoes)); } }
    }

}
