//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class DetalleVenta : XPObject
    {
        DetalleCobros fDetalleCobro;
        [Association(@"DetalleVentaReferencesDetalleCobros")]
        public DetalleCobros DetalleCobro
        {
            get { return fDetalleCobro; }
            set { SetPropertyValue<DetalleCobros>(nameof(DetalleCobro), ref fDetalleCobro, value); }
        }
        decimal fIva;
        public decimal Iva
        {
            get { return fIva; }
            set { SetPropertyValue<decimal>(nameof(Iva), ref fIva, value); }
        }
        decimal fDescuento;
        public decimal Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<decimal>(nameof(Descuento), ref fDescuento, value); }
        }
        decimal fMontoFactura;
        public decimal MontoFactura
        {
            get { return fMontoFactura; }
            set { SetPropertyValue<decimal>(nameof(MontoFactura), ref fMontoFactura, value); }
        }
        Venta fVenta;
        [Association(@"DetalleVentaReferencesVenta")]
        public Venta Venta
        {
            get { return fVenta; }
            set { SetPropertyValue<Venta>(nameof(Venta), ref fVenta, value); }
        }
        CobroPendiente fComanda;
        [Association(@"DetalleVentaReferencesCobroPendiente")]
        public CobroPendiente Comanda
        {
            get { return fComanda; }
            set { SetPropertyValue<CobroPendiente>(nameof(Comanda), ref fComanda, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        decimal fGravado;
        public decimal Gravado
        {
            get { return fGravado; }
            set { SetPropertyValue<decimal>(nameof(Gravado), ref fGravado, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        ReporteCxcEmpleado fReporteEmpleado;
        [Association(@"DetalleVentaReferencesReporteCxcEmpleado")]
        public ReporteCxcEmpleado ReporteEmpleado
        {
            get { return fReporteEmpleado; }
            set { SetPropertyValue<ReporteCxcEmpleado>(nameof(ReporteEmpleado), ref fReporteEmpleado, value); }
        }
    }

}
