//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class DetallePago : XPObject
    {
        Venta fVenta;
        [Association(@"DetallePagoReferencesVenta")]
        public Venta Venta
        {
            get { return fVenta; }
            set { SetPropertyValue<Venta>(nameof(Venta), ref fVenta, value); }
        }
        FormaDePago fFormaDePago;
        [Association(@"DetallePagoReferencesFormaDePago")]
        public FormaDePago FormaDePago
        {
            get { return fFormaDePago; }
            set { SetPropertyValue<FormaDePago>(nameof(FormaDePago), ref fFormaDePago, value); }
        }
        decimal fMonto;
        public decimal Monto
        {
            get { return fMonto; }
            set { SetPropertyValue<decimal>(nameof(Monto), ref fMonto, value); }
        }
    }

}
