//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Direccion : XPObject
    {
        Pais fPais;
        [Association(@"DireccionReferencesPais")]
        public Pais Pais
        {
            get { return fPais; }
            set { SetPropertyValue<Pais>(nameof(Pais), ref fPais, value); }
        }
        Estado fEstado;
        [Association(@"DireccionReferencesEstado")]
        public Estado Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<Estado>(nameof(Estado), ref fEstado, value); }
        }
        Ciudad fCiudad;
        [Association(@"DireccionReferencesCiudad")]
        public Ciudad Ciudad
        {
            get { return fCiudad; }
            set { SetPropertyValue<Ciudad>(nameof(Ciudad), ref fCiudad, value); }
        }
        string fCodigoPostal;
        public string CodigoPostal
        {
            get { return fCodigoPostal; }
            set { SetPropertyValue<string>(nameof(CodigoPostal), ref fCodigoPostal, value); }
        }
        string fCalle;
        public string Calle
        {
            get { return fCalle; }
            set { SetPropertyValue<string>(nameof(Calle), ref fCalle, value); }
        }
        string fDireccionCompleta;
        public string DireccionCompleta
        {
            get { return fDireccionCompleta; }
            set { SetPropertyValue<string>(nameof(DireccionCompleta), ref fDireccionCompleta, value); }
        }
        [Association(@"EmpresaReferencesDireccion")]
        public XPCollection<Empresa> Empresas { get { return GetCollection<Empresa>(nameof(Empresas)); } }
        [Association(@"EntidadReferencesDireccion")]
        public XPCollection<Entidad> Entidads { get { return GetCollection<Entidad>(nameof(Entidads)); } }
    }

}
