//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Empleado : XPObject
    {
        Sucursal fSucursal;
        [Association(@"EmpleadoReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fNit;
        public string Nit
        {
            get { return fNit; }
            set { SetPropertyValue<string>(nameof(Nit), ref fNit, value); }
        }
        string fDui;
        public string Dui
        {
            get { return fDui; }
            set { SetPropertyValue<string>(nameof(Dui), ref fDui, value); }
        }
        int fPuesto;
        public int Puesto
        {
            get { return fPuesto; }
            set { SetPropertyValue<int>(nameof(Puesto), ref fPuesto, value); }
        }
        DateTime fFechaContratacion;
        public DateTime FechaContratacion
        {
            get { return fFechaContratacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaContratacion), ref fFechaContratacion, value); }
        }
        int fOidSamba;
        public int OidSamba
        {
            get { return fOidSamba; }
            set { SetPropertyValue<int>(nameof(OidSamba), ref fOidSamba, value); }
        }
        decimal fSalario;
        public decimal Salario
        {
            get { return fSalario; }
            set { SetPropertyValue<decimal>(nameof(Salario), ref fSalario, value); }
        }
        UnidadOrganizativa fUnidadOrganizativa;
        [Association(@"EmpleadoReferencesUnidadOrganizativa")]
        public UnidadOrganizativa UnidadOrganizativa
        {
            get { return fUnidadOrganizativa; }
            set { SetPropertyValue<UnidadOrganizativa>(nameof(UnidadOrganizativa), ref fUnidadOrganizativa, value); }
        }
        [Association(@"CobroPendienteReferencesEmpleado")]
        public XPCollection<CobroPendiente> CobroPendientes { get { return GetCollection<CobroPendiente>(nameof(CobroPendientes)); } }
        [Association(@"CuentaServiciosReferencesEmpleado")]
        public XPCollection<CuentaServicios> CuentaServiciosCollection { get { return GetCollection<CuentaServicios>(nameof(CuentaServiciosCollection)); } }
        [Association(@"DetalleCobrosReferencesEmpleado")]
        public XPCollection<DetalleCobros> DetalleCobrosCollection { get { return GetCollection<DetalleCobros>(nameof(DetalleCobrosCollection)); } }
        [Association(@"ReporteCxcEmpleadoReferencesEmpleado")]
        public XPCollection<ReporteCxcEmpleado> ReporteCxcEmpleadoes { get { return GetCollection<ReporteCxcEmpleado>(nameof(ReporteCxcEmpleadoes)); } }
        [Association(@"UsuarioReferencesEmpleado")]
        public XPCollection<Usuario> Usuarios { get { return GetCollection<Usuario>(nameof(Usuarios)); } }
    }

}
