//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Empresa : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        Direccion fDireccioon;
        [Association(@"EmpresaReferencesDireccion")]
        public Direccion Direccioon
        {
            get { return fDireccioon; }
            set { SetPropertyValue<Direccion>(nameof(Direccioon), ref fDireccioon, value); }
        }
        string fRegistroFiscal;
        public string RegistroFiscal
        {
            get { return fRegistroFiscal; }
            set { SetPropertyValue<string>(nameof(RegistroFiscal), ref fRegistroFiscal, value); }
        }
        string fTelefono;
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        string fTipoContribuyente;
        public string TipoContribuyente
        {
            get { return fTipoContribuyente; }
            set { SetPropertyValue<string>(nameof(TipoContribuyente), ref fTipoContribuyente, value); }
        }
        string fNoContribuyente;
        public string NoContribuyente
        {
            get { return fNoContribuyente; }
            set { SetPropertyValue<string>(nameof(NoContribuyente), ref fNoContribuyente, value); }
        }
        string fLogoEmpresa;
        public string LogoEmpresa
        {
            get { return fLogoEmpresa; }
            set { SetPropertyValue<string>(nameof(LogoEmpresa), ref fLogoEmpresa, value); }
        }
        string fRazonSocial;
        public string RazonSocial
        {
            get { return fRazonSocial; }
            set { SetPropertyValue<string>(nameof(RazonSocial), ref fRazonSocial, value); }
        }
        string fGiro;
        public string Giro
        {
            get { return fGiro; }
            set { SetPropertyValue<string>(nameof(Giro), ref fGiro, value); }
        }
        string fNoDocPersonal;
        public string NoDocPersonal
        {
            get { return fNoDocPersonal; }
            set { SetPropertyValue<string>(nameof(NoDocPersonal), ref fNoDocPersonal, value); }
        }
    }

}
