//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Estado : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        Pais fPais;
        [Association(@"EstadoReferencesPais")]
        public Pais Pais
        {
            get { return fPais; }
            set { SetPropertyValue<Pais>(nameof(Pais), ref fPais, value); }
        }
        [Association(@"CiudadReferencesEstado")]
        public XPCollection<Ciudad> Ciudads { get { return GetCollection<Ciudad>(nameof(Ciudads)); } }
        [Association(@"DireccionReferencesEstado")]
        public XPCollection<Direccion> Direccions { get { return GetCollection<Direccion>(nameof(Direccions)); } }
    }

}
