//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class EstadoHabitacion : XPObject
    {
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        Habitacion fHabitacion;
        [Association(@"EstadoHabitacionReferencesHabitacion")]
        public Habitacion Habitacion
        {
            get { return fHabitacion; }
            set { SetPropertyValue<Habitacion>(nameof(Habitacion), ref fHabitacion, value); }
        }
        int fEstadoActual;
        public int EstadoActual
        {
            get { return fEstadoActual; }
            set { SetPropertyValue<int>(nameof(EstadoActual), ref fEstadoActual, value); }
        }
        int fEstadoAnterior;
        public int EstadoAnterior
        {
            get { return fEstadoAnterior; }
            set { SetPropertyValue<int>(nameof(EstadoAnterior), ref fEstadoAnterior, value); }
        }
        bool fActivo;
        public bool Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<bool>(nameof(Activo), ref fActivo, value); }
        }
    }

}
