//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class FormaDePago : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fTipoDePago;
        public string TipoDePago
        {
            get { return fTipoDePago; }
            set { SetPropertyValue<string>(nameof(TipoDePago), ref fTipoDePago, value); }
        }
        [Association(@"DetallePagoReferencesFormaDePago")]
        public XPCollection<DetallePago> DetallePagoes { get { return GetCollection<DetallePago>(nameof(DetallePagoes)); } }
    }

}
