//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Habitacion : XPObject
    {
        TarifaHabitacion fTipoHabitacion;
        [Association(@"HabitacionReferencesTarifaHabitacion")]
        public TarifaHabitacion TipoHabitacion
        {
            get { return fTipoHabitacion; }
            set { SetPropertyValue<TarifaHabitacion>(nameof(TipoHabitacion), ref fTipoHabitacion, value); }
        }
        int fNumero;
        public int Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<int>(nameof(Numero), ref fNumero, value); }
        }
        int fCapacidadMenores;
        public int CapacidadMenores
        {
            get { return fCapacidadMenores; }
            set { SetPropertyValue<int>(nameof(CapacidadMenores), ref fCapacidadMenores, value); }
        }
        int fCapacidadMayores;
        public int CapacidadMayores
        {
            get { return fCapacidadMayores; }
            set { SetPropertyValue<int>(nameof(CapacidadMayores), ref fCapacidadMayores, value); }
        }
        string fUbicacion;
        public string Ubicacion
        {
            get { return fUbicacion; }
            set { SetPropertyValue<string>(nameof(Ubicacion), ref fUbicacion, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        int fNivelEdificio;
        public int NivelEdificio
        {
            get { return fNivelEdificio; }
            set { SetPropertyValue<int>(nameof(NivelEdificio), ref fNivelEdificio, value); }
        }
        [Association(@"AccesorioHabitacionReferencesHabitacion")]
        public XPCollection<AccesorioHabitacion> AccesorioHabitacions { get { return GetCollection<AccesorioHabitacion>(nameof(AccesorioHabitacions)); } }
        [Association(@"AsignacionUsuarioLimpiezaReferencesHabitacion")]
        public XPCollection<AsignacionUsuarioLimpieza> AsignacionUsuarioLimpiezas { get { return GetCollection<AsignacionUsuarioLimpieza>(nameof(AsignacionUsuarioLimpiezas)); } }
        [Association(@"EstadoHabitacionReferencesHabitacion")]
        public XPCollection<EstadoHabitacion> EstadoHabitacions { get { return GetCollection<EstadoHabitacion>(nameof(EstadoHabitacions)); } }
        [Association(@"ReservacionHabitacionReferencesHabitacion")]
        public XPCollection<ReservacionHabitacion> ReservacionHabitacions { get { return GetCollection<ReservacionHabitacion>(nameof(ReservacionHabitacions)); } }
        [Association(@"ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollectionReferencesHabitacion")]
        public XPCollection<ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollection> ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollections { get { return GetCollection<ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollection>(nameof(ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollections)); } }
    }

}
