//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Pais : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        [Association(@"DireccionReferencesPais")]
        public XPCollection<Direccion> Direccions { get { return GetCollection<Direccion>(nameof(Direccions)); } }
        [Association(@"EntidadReferencesPais")]
        public XPCollection<Entidad> Entidads { get { return GetCollection<Entidad>(nameof(Entidads)); } }
        [Association(@"EstadoReferencesPais")]
        public XPCollection<Estado> Estadoes { get { return GetCollection<Estado>(nameof(Estadoes)); } }
    }

}
