//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class PreciosTarifas : XPObject
    {
        bool fActivo;
        public bool Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<bool>(nameof(Activo), ref fActivo, value); }
        }
        decimal fPrecio;
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
        TarifaHabitacion fTarifa;
        [Association(@"PreciosTarifasReferencesTarifaHabitacion")]
        public TarifaHabitacion Tarifa
        {
            get { return fTarifa; }
            set { SetPropertyValue<TarifaHabitacion>(nameof(Tarifa), ref fTarifa, value); }
        }
        bool fBase;
        public bool Base
        {
            get { return fBase; }
            set { SetPropertyValue<bool>(nameof(Base), ref fBase, value); }
        }
    }

}
