//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class PromocionHotel : XPObject
    {
        DateTime fInicioPromocion;
        public DateTime InicioPromocion
        {
            get { return fInicioPromocion; }
            set { SetPropertyValue<DateTime>(nameof(InicioPromocion), ref fInicioPromocion, value); }
        }
        DateTime fFinPromocion;
        public DateTime FinPromocion
        {
            get { return fFinPromocion; }
            set { SetPropertyValue<DateTime>(nameof(FinPromocion), ref fFinPromocion, value); }
        }
        DateTime fInicioReservaciones;
        public DateTime InicioReservaciones
        {
            get { return fInicioReservaciones; }
            set { SetPropertyValue<DateTime>(nameof(InicioReservaciones), ref fInicioReservaciones, value); }
        }
        DateTime fFinReservaciones;
        public DateTime FinReservaciones
        {
            get { return fFinReservaciones; }
            set { SetPropertyValue<DateTime>(nameof(FinReservaciones), ref fFinReservaciones, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"ReservacionHotelReferencesPromocionHotel")]
        public XPCollection<ReservacionHotel> ReservacionHotels { get { return GetCollection<ReservacionHotel>(nameof(ReservacionHotels)); } }
        [Association(@"TarifaPromocionReferencesPromocionHotel")]
        public XPCollection<TarifaPromocion> TarifaPromocions { get { return GetCollection<TarifaPromocion>(nameof(TarifaPromocions)); } }
    }

}
