//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReporteTurnos : XPObject
    {
        DateTime fFechaInicio;
        public DateTime FechaInicio
        {
            get { return fFechaInicio; }
            set { SetPropertyValue<DateTime>(nameof(FechaInicio), ref fFechaInicio, value); }
        }
        DateTime fFechaFin;
        public DateTime FechaFin
        {
            get { return fFechaFin; }
            set { SetPropertyValue<DateTime>(nameof(FechaFin), ref fFechaFin, value); }
        }
        bool fImprimir;
        public bool Imprimir
        {
            get { return fImprimir; }
            set { SetPropertyValue<bool>(nameof(Imprimir), ref fImprimir, value); }
        }
        [Association(@"TurnoReferencesReporteTurnos")]
        public XPCollection<Turno> Turnoes { get { return GetCollection<Turno>(nameof(Turnoes)); } }
    }

}
