//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReporteCxcEmpleado : XPObject
    {
        Empleado fEmpleado;
        [Association(@"ReporteCxcEmpleadoReferencesEmpleado")]
        public Empleado Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(Empleado), ref fEmpleado, value); }
        }
        DateTime fFechaElaborado;
        public DateTime FechaElaborado
        {
            get { return fFechaElaborado; }
            set { SetPropertyValue<DateTime>(nameof(FechaElaborado), ref fFechaElaborado, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        bool fImprimir;
        public bool Imprimir
        {
            get { return fImprimir; }
            set { SetPropertyValue<bool>(nameof(Imprimir), ref fImprimir, value); }
        }
        DateTime fFechaInicio;
        public DateTime FechaInicio
        {
            get { return fFechaInicio; }
            set { SetPropertyValue<DateTime>(nameof(FechaInicio), ref fFechaInicio, value); }
        }
        DateTime fFechaFin;
        public DateTime FechaFin
        {
            get { return fFechaFin; }
            set { SetPropertyValue<DateTime>(nameof(FechaFin), ref fFechaFin, value); }
        }
        [Association(@"CobroPendienteReferencesReporteCxcEmpleado")]
        public XPCollection<CobroPendiente> CobroPendientes { get { return GetCollection<CobroPendiente>(nameof(CobroPendientes)); } }
        [Association(@"DetalleVentaReferencesReporteCxcEmpleado")]
        public XPCollection<DetalleVenta> DetalleVentas { get { return GetCollection<DetalleVenta>(nameof(DetalleVentas)); } }
    }

}
