//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReservacionHabitacion : XPObject
    {
        Habitacion fHabitacion;
        [Association(@"ReservacionHabitacionReferencesHabitacion")]
        public Habitacion Habitacion
        {
            get { return fHabitacion; }
            set { SetPropertyValue<Habitacion>(nameof(Habitacion), ref fHabitacion, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        decimal fDescuento;
        public decimal Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<decimal>(nameof(Descuento), ref fDescuento, value); }
        }
        ReservacionHotel fReservacion;
        [Association(@"ReservacionHabitacionReferencesReservacionHotel")]
        public ReservacionHotel Reservacion
        {
            get { return fReservacion; }
            set { SetPropertyValue<ReservacionHotel>(nameof(Reservacion), ref fReservacion, value); }
        }
    }

}
