//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReservacionHotel : XPObject
    {
        Entidad fCliente;
        [Association(@"ReservacionHotelReferencesEntidad")]
        public Entidad Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<Entidad>(nameof(Cliente), ref fCliente, value); }
        }
        DateTime fFechaEntrada;
        public DateTime FechaEntrada
        {
            get { return fFechaEntrada; }
            set { SetPropertyValue<DateTime>(nameof(FechaEntrada), ref fFechaEntrada, value); }
        }
        DateTime fFechaSalida;
        public DateTime FechaSalida
        {
            get { return fFechaSalida; }
            set { SetPropertyValue<DateTime>(nameof(FechaSalida), ref fFechaSalida, value); }
        }
        int fNiños;
        public int Niños
        {
            get { return fNiños; }
            set { SetPropertyValue<int>(nameof(Niños), ref fNiños, value); }
        }
        int fAdultos;
        public int Adultos
        {
            get { return fAdultos; }
            set { SetPropertyValue<int>(nameof(Adultos), ref fAdultos, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        string fCodigoReservacion;
        public string CodigoReservacion
        {
            get { return fCodigoReservacion; }
            set { SetPropertyValue<string>(nameof(CodigoReservacion), ref fCodigoReservacion, value); }
        }
        string fNumeroVuelo;
        public string NumeroVuelo
        {
            get { return fNumeroVuelo; }
            set { SetPropertyValue<string>(nameof(NumeroVuelo), ref fNumeroVuelo, value); }
        }
        string fAerolinea;
        public string Aerolinea
        {
            get { return fAerolinea; }
            set { SetPropertyValue<string>(nameof(Aerolinea), ref fAerolinea, value); }
        }
        DateTime fFechaLlegada;
        public DateTime FechaLlegada
        {
            get { return fFechaLlegada; }
            set { SetPropertyValue<DateTime>(nameof(FechaLlegada), ref fFechaLlegada, value); }
        }
        DateTime fFechaReservacion;
        public DateTime FechaReservacion
        {
            get { return fFechaReservacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaReservacion), ref fFechaReservacion, value); }
        }
        DateTime fHoraCheckIn;
        public DateTime HoraCheckIn
        {
            get { return fHoraCheckIn; }
            set { SetPropertyValue<DateTime>(nameof(HoraCheckIn), ref fHoraCheckIn, value); }
        }
        DateTime fHoraCheckOut;
        public DateTime HoraCheckOut
        {
            get { return fHoraCheckOut; }
            set { SetPropertyValue<DateTime>(nameof(HoraCheckOut), ref fHoraCheckOut, value); }
        }
        PromocionHotel fPromocion;
        [Association(@"ReservacionHotelReferencesPromocionHotel")]
        public PromocionHotel Promocion
        {
            get { return fPromocion; }
            set { SetPropertyValue<PromocionHotel>(nameof(Promocion), ref fPromocion, value); }
        }
        DateTime fFechaAnulado;
        public DateTime FechaAnulado
        {
            get { return fFechaAnulado; }
            set { SetPropertyValue<DateTime>(nameof(FechaAnulado), ref fFechaAnulado, value); }
        }
        string fDescripcionAnulado;
        public string DescripcionAnulado
        {
            get { return fDescripcionAnulado; }
            set { SetPropertyValue<string>(nameof(DescripcionAnulado), ref fDescripcionAnulado, value); }
        }
        CuentaServicios fCuentaServicio;
        [Association(@"ReservacionHotelReferencesCuentaServicios")]
        public CuentaServicios CuentaServicio
        {
            get { return fCuentaServicio; }
            set { SetPropertyValue<CuentaServicios>(nameof(CuentaServicio), ref fCuentaServicio, value); }
        }
        [Association(@"ReservacionHabitacionReferencesReservacionHotel")]
        public XPCollection<ReservacionHabitacion> ReservacionHabitacions { get { return GetCollection<ReservacionHabitacion>(nameof(ReservacionHabitacions)); } }
        [Association(@"ReservacionTarifasReferencesReservacionHotel")]
        public XPCollection<ReservacionTarifas> ReservacionTarifasCollection { get { return GetCollection<ReservacionTarifas>(nameof(ReservacionTarifasCollection)); } }
        [Association(@"ServicioExtraReservacionHotelReferencesReservacionHotel")]
        public XPCollection<ServicioExtraReservacionHotel> ServicioExtraReservacionHotels { get { return GetCollection<ServicioExtraReservacionHotel>(nameof(ServicioExtraReservacionHotels)); } }
    }

}
