//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReservacionVehiculo : XPObject
    {
        RentaVehiculo fReservacion;
        [Association(@"ReservacionVehiculoReferencesRentaVehiculo")]
        public RentaVehiculo Reservacion
        {
            get { return fReservacion; }
            set { SetPropertyValue<RentaVehiculo>(nameof(Reservacion), ref fReservacion, value); }
        }
        Vehiculo fVehiculo;
        [Association(@"ReservacionVehiculoReferencesVehiculo")]
        public Vehiculo Vehiculo
        {
            get { return fVehiculo; }
            set { SetPropertyValue<Vehiculo>(nameof(Vehiculo), ref fVehiculo, value); }
        }
        decimal fPrecio;
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
    }

}
