//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ReservacionTarifas : XPObject
    {
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        decimal fDescuento;
        public decimal Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<decimal>(nameof(Descuento), ref fDescuento, value); }
        }
        ReservacionHotel fReservacion;
        [Association(@"ReservacionTarifasReferencesReservacionHotel")]
        public ReservacionHotel Reservacion
        {
            get { return fReservacion; }
            set { SetPropertyValue<ReservacionHotel>(nameof(Reservacion), ref fReservacion, value); }
        }
        int fCantidadHabitaciones;
        public int CantidadHabitaciones
        {
            get { return fCantidadHabitaciones; }
            set { SetPropertyValue<int>(nameof(CantidadHabitaciones), ref fCantidadHabitaciones, value); }
        }
        TarifaHabitacion fTarifa;
        [Association(@"ReservacionTarifasReferencesTarifaHabitacion")]
        public TarifaHabitacion Tarifa
        {
            get { return fTarifa; }
            set { SetPropertyValue<TarifaHabitacion>(nameof(Tarifa), ref fTarifa, value); }
        }
        [Association(@"ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollectionReferencesReservacionTarifas")]
        public XPCollection<ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollection> ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollections { get { return GetCollection<ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollection>(nameof(ReservacionTarifasReservacionTarifasCollection_HabitacionHabitacionCollections)); } }
    }

}
