//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Roles : XPObject
    {
        string fTipoUsuario;
        public string TipoUsuario
        {
            get { return fTipoUsuario; }
            set { SetPropertyValue<string>(nameof(TipoUsuario), ref fTipoUsuario, value); }
        }
        int fNivelDeAcceso;
        public int NivelDeAcceso
        {
            get { return fNivelDeAcceso; }
            set { SetPropertyValue<int>(nameof(NivelDeAcceso), ref fNivelDeAcceso, value); }
        }
        [Association(@"UsuarioReferencesRoles")]
        public XPCollection<Usuario> Usuarios { get { return GetCollection<Usuario>(nameof(Usuarios)); } }
    }

}
