//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class ServicioExtraReservacionHotel : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        decimal fPrecioUnitario;
        public decimal PrecioUnitario
        {
            get { return fPrecioUnitario; }
            set { SetPropertyValue<decimal>(nameof(PrecioUnitario), ref fPrecioUnitario, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        decimal fPrecio;
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
        ReservacionHotel fReservacionHotel;
        [Association(@"ServicioExtraReservacionHotelReferencesReservacionHotel")]
        public ReservacionHotel ReservacionHotel
        {
            get { return fReservacionHotel; }
            set { SetPropertyValue<ReservacionHotel>(nameof(ReservacionHotel), ref fReservacionHotel, value); }
        }
        string fFechaCreacion;
        public string FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<string>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        string fDetalleCobro;
        public string DetalleCobro
        {
            get { return fDetalleCobro; }
            set { SetPropertyValue<string>(nameof(DetalleCobro), ref fDetalleCobro, value); }
        }
    }

}
