//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Sesiones : XPObject
    {
        DateTime fFechaEntrada;
        public DateTime FechaEntrada
        {
            get { return fFechaEntrada; }
            set { SetPropertyValue<DateTime>(nameof(FechaEntrada), ref fFechaEntrada, value); }
        }
        DateTime fFechaSalida;
        public DateTime FechaSalida
        {
            get { return fFechaSalida; }
            set { SetPropertyValue<DateTime>(nameof(FechaSalida), ref fFechaSalida, value); }
        }
        Usuario fUsuario;
        [Association(@"SesionesReferencesUsuario")]
        public Usuario Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<Usuario>(nameof(Usuario), ref fUsuario, value); }
        }
        bool fAbierto;
        public bool Abierto
        {
            get { return fAbierto; }
            set { SetPropertyValue<bool>(nameof(Abierto), ref fAbierto, value); }
        }
        Turno fTurno;
        [Association(@"SesionesReferencesTurno")]
        public Turno Turno
        {
            get { return fTurno; }
            set { SetPropertyValue<Turno>(nameof(Turno), ref fTurno, value); }
        }
        [Association(@"TransaccionReferencesSesiones")]
        public XPCollection<Transaccion> Transaccions { get { return GetCollection<Transaccion>(nameof(Transaccions)); } }
    }

}
