//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class TarifaPromocion : XPObject
    {
        TarifaHabitacion fTarifa;
        [Association(@"TarifaPromocionReferencesTarifaHabitacion")]
        public TarifaHabitacion Tarifa
        {
            get { return fTarifa; }
            set { SetPropertyValue<TarifaHabitacion>(nameof(Tarifa), ref fTarifa, value); }
        }
        PromocionHotel fPromocion;
        [Association(@"TarifaPromocionReferencesPromocionHotel")]
        public PromocionHotel Promocion
        {
            get { return fPromocion; }
            set { SetPropertyValue<PromocionHotel>(nameof(Promocion), ref fPromocion, value); }
        }
        decimal fPrecioPromocionTarifa;
        public decimal PrecioPromocionTarifa
        {
            get { return fPrecioPromocionTarifa; }
            set { SetPropertyValue<decimal>(nameof(PrecioPromocionTarifa), ref fPrecioPromocionTarifa, value); }
        }
    }

}
