//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class TarifasVehiculo : XPObject
    {
        int fMinimoDias;
        public int MinimoDias
        {
            get { return fMinimoDias; }
            set { SetPropertyValue<int>(nameof(MinimoDias), ref fMinimoDias, value); }
        }
        int fMaximoDias;
        public int MaximoDias
        {
            get { return fMaximoDias; }
            set { SetPropertyValue<int>(nameof(MaximoDias), ref fMaximoDias, value); }
        }
        decimal fPrecio;
        public decimal Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<decimal>(nameof(Precio), ref fPrecio, value); }
        }
        Vehiculo fVehiculo;
        [Association(@"TarifasVehiculoReferencesVehiculo")]
        public Vehiculo Vehiculo
        {
            get { return fVehiculo; }
            set { SetPropertyValue<Vehiculo>(nameof(Vehiculo), ref fVehiculo, value); }
        }
    }

}
