//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class TipoImpuesto : XPObject
    {
        Venta fVenta;
        [Association(@"TipoImpuestoReferencesVenta")]
        public Venta Venta
        {
            get { return fVenta; }
            set { SetPropertyValue<Venta>(nameof(Venta), ref fVenta, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        double fPorcentaje;
        public double Porcentaje
        {
            get { return fPorcentaje; }
            set { SetPropertyValue<double>(nameof(Porcentaje), ref fPorcentaje, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
    }

}
