//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class TipoDocumento : XPObject
    {
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fNombreReporte;
        public string NombreReporte
        {
            get { return fNombreReporte; }
            set { SetPropertyValue<string>(nameof(NombreReporte), ref fNombreReporte, value); }
        }
        string fAbreviatura;
        public string Abreviatura
        {
            get { return fAbreviatura; }
            set { SetPropertyValue<string>(nameof(Abreviatura), ref fAbreviatura, value); }
        }
        int fDocumento;
        public int Documento
        {
            get { return fDocumento; }
            set { SetPropertyValue<int>(nameof(Documento), ref fDocumento, value); }
        }
        Sucursal fSucursal;
        [Association(@"TipoDocumentoReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        string fNombreImpresora;
        public string NombreImpresora
        {
            get { return fNombreImpresora; }
            set { SetPropertyValue<string>(nameof(NombreImpresora), ref fNombreImpresora, value); }
        }
        RangoDocumento fRangoActivo;
        [Association(@"TipoDocumentoReferencesRangoDocumento")]
        public RangoDocumento RangoActivo
        {
            get { return fRangoActivo; }
            set { SetPropertyValue<RangoDocumento>(nameof(RangoActivo), ref fRangoActivo, value); }
        }
        [Association(@"RangoDocumentoReferencesTipoDocumento")]
        public XPCollection<RangoDocumento> RangoDocumentoes { get { return GetCollection<RangoDocumento>(nameof(RangoDocumentoes)); } }
        [Association(@"VentaReferencesTipoDocumento")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
