//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Transaccion : XPObject
    {
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fTipoTransaccion;
        public string TipoTransaccion
        {
            get { return fTipoTransaccion; }
            set { SetPropertyValue<string>(nameof(TipoTransaccion), ref fTipoTransaccion, value); }
        }
        Sesiones fSesion;
        [Association(@"TransaccionReferencesSesiones")]
        public Sesiones Sesion
        {
            get { return fSesion; }
            set { SetPropertyValue<Sesiones>(nameof(Sesion), ref fSesion, value); }
        }
        [Association(@"VentaReferencesTransaccion")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
