//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Turno : XPObject
    {
        DateTime fFechaInicio;
        public DateTime FechaInicio
        {
            get { return fFechaInicio; }
            set { SetPropertyValue<DateTime>(nameof(FechaInicio), ref fFechaInicio, value); }
        }
        DateTime fFechaFin;
        public DateTime FechaFin
        {
            get { return fFechaFin; }
            set { SetPropertyValue<DateTime>(nameof(FechaFin), ref fFechaFin, value); }
        }
        Usuario fUsuario;
        [Association(@"TurnoReferencesUsuario")]
        public Usuario Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<Usuario>(nameof(Usuario), ref fUsuario, value); }
        }
        bool fActivo;
        public bool Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<bool>(nameof(Activo), ref fActivo, value); }
        }
        bool fAbierto;
        public bool Abierto
        {
            get { return fAbierto; }
            set { SetPropertyValue<bool>(nameof(Abierto), ref fAbierto, value); }
        }
        Sucursal fSucursal;
        [Association(@"TurnoReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        int fPuestoTrabajo;
        public int PuestoTrabajo
        {
            get { return fPuestoTrabajo; }
            set { SetPropertyValue<int>(nameof(PuestoTrabajo), ref fPuestoTrabajo, value); }
        }
        ReporteTurnos fReporteTurno;
        [Association(@"TurnoReferencesReporteTurnos")]
        public ReporteTurnos ReporteTurno
        {
            get { return fReporteTurno; }
            set { SetPropertyValue<ReporteTurnos>(nameof(ReporteTurno), ref fReporteTurno, value); }
        }
        [Association(@"CobroPendienteReferencesTurno")]
        public XPCollection<CobroPendiente> CobroPendientes { get { return GetCollection<CobroPendiente>(nameof(CobroPendientes)); } }
        [Association(@"CorteDeCajaReferencesTurno")]
        public XPCollection<CorteDeCaja> CorteDeCajas { get { return GetCollection<CorteDeCaja>(nameof(CorteDeCajas)); } }
        [Association(@"SesionesReferencesTurno")]
        public XPCollection<Sesiones> SesionesCollection { get { return GetCollection<Sesiones>(nameof(SesionesCollection)); } }
        [Association(@"VentaReferencesTurno")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
        [Association(@"VentaReferencesTurno1")]
        public XPCollection<Venta> Ventas1 { get { return GetCollection<Venta>(nameof(Ventas1)); } }
    }

}
