//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class UnidadMedida : XPObject
    {
        Articulo fArticulo;
        [Association(@"UnidadMedidaReferencesArticulo")]
        public Articulo Articulo
        {
            get { return fArticulo; }
            set { SetPropertyValue<Articulo>(nameof(Articulo), ref fArticulo, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fAbreviatura;
        public string Abreviatura
        {
            get { return fAbreviatura; }
            set { SetPropertyValue<string>(nameof(Abreviatura), ref fAbreviatura, value); }
        }
    }

}
