//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Usuario : XPObject
    {
        Sucursal fSucursal;
        [Association(@"UsuarioReferencesSucursal")]
        public Sucursal Sucursal
        {
            get { return fSucursal; }
            set { SetPropertyValue<Sucursal>(nameof(Sucursal), ref fSucursal, value); }
        }
        Empleado fEmpleado;
        [Association(@"UsuarioReferencesEmpleado")]
        public Empleado Empleado
        {
            get { return fEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(Empleado), ref fEmpleado, value); }
        }
        string fNombreUsuario;
        public string NombreUsuario
        {
            get { return fNombreUsuario; }
            set { SetPropertyValue<string>(nameof(NombreUsuario), ref fNombreUsuario, value); }
        }
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        Roles fRol;
        [Association(@"UsuarioReferencesRoles")]
        public Roles Rol
        {
            get { return fRol; }
            set { SetPropertyValue<Roles>(nameof(Rol), ref fRol, value); }
        }
        bool fActivo;
        public bool Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<bool>(nameof(Activo), ref fActivo, value); }
        }
        byte[] fHash;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Hash
        {
            get { return fHash; }
            set { SetPropertyValue<byte[]>(nameof(Hash), ref fHash, value); }
        }
        byte[] fSalt;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Salt
        {
            get { return fSalt; }
            set { SetPropertyValue<byte[]>(nameof(Salt), ref fSalt, value); }
        }
        int fFuncion;
        public int Funcion
        {
            get { return fFuncion; }
            set { SetPropertyValue<int>(nameof(Funcion), ref fFuncion, value); }
        }
        [Association(@"AnulacionCobroReferencesUsuario")]
        public XPCollection<AnulacionCobro> AnulacionCobroes { get { return GetCollection<AnulacionCobro>(nameof(AnulacionCobroes)); } }
        [Association(@"AnulacionCobroReferencesUsuario1")]
        public XPCollection<AnulacionCobro> AnulacionCobroes1 { get { return GetCollection<AnulacionCobro>(nameof(AnulacionCobroes1)); } }
        [Association(@"AsignacionUsuarioLimpiezaReferencesUsuario")]
        public XPCollection<AsignacionUsuarioLimpieza> AsignacionUsuarioLimpiezas { get { return GetCollection<AsignacionUsuarioLimpieza>(nameof(AsignacionUsuarioLimpiezas)); } }
        [Association(@"SesionesReferencesUsuario")]
        public XPCollection<Sesiones> SesionesCollection { get { return GetCollection<Sesiones>(nameof(SesionesCollection)); } }
        [Association(@"TurnoReferencesUsuario")]
        public XPCollection<Turno> Turnoes { get { return GetCollection<Turno>(nameof(Turnoes)); } }
    }

}
