//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafReports.Module.BusinessObjects.Business
{

    public partial class Vehiculo : XPObject
    {
        string fMarca;
        public string Marca
        {
            get { return fMarca; }
            set { SetPropertyValue<string>(nameof(Marca), ref fMarca, value); }
        }
        string fModelo;
        public string Modelo
        {
            get { return fModelo; }
            set { SetPropertyValue<string>(nameof(Modelo), ref fModelo, value); }
        }
        string fColor;
        public string Color
        {
            get { return fColor; }
            set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
        }
        int fTipo;
        public int Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<int>(nameof(Tipo), ref fTipo, value); }
        }
        string fClase;
        public string Clase
        {
            get { return fClase; }
            set { SetPropertyValue<string>(nameof(Clase), ref fClase, value); }
        }
        int fCombustible;
        public int Combustible
        {
            get { return fCombustible; }
            set { SetPropertyValue<int>(nameof(Combustible), ref fCombustible, value); }
        }
        string fTransmision;
        public string Transmision
        {
            get { return fTransmision; }
            set { SetPropertyValue<string>(nameof(Transmision), ref fTransmision, value); }
        }
        string fTraccion;
        public string Traccion
        {
            get { return fTraccion; }
            set { SetPropertyValue<string>(nameof(Traccion), ref fTraccion, value); }
        }
        string fMotor;
        public string Motor
        {
            get { return fMotor; }
            set { SetPropertyValue<string>(nameof(Motor), ref fMotor, value); }
        }
        string fTarjetaCirculacion;
        public string TarjetaCirculacion
        {
            get { return fTarjetaCirculacion; }
            set { SetPropertyValue<string>(nameof(TarjetaCirculacion), ref fTarjetaCirculacion, value); }
        }
        int fAño;
        public int Año
        {
            get { return fAño; }
            set { SetPropertyValue<int>(nameof(Año), ref fAño, value); }
        }
        string fPlaca;
        public string Placa
        {
            get { return fPlaca; }
            set { SetPropertyValue<string>(nameof(Placa), ref fPlaca, value); }
        }
        int fCapacidad;
        public int Capacidad
        {
            get { return fCapacidad; }
            set { SetPropertyValue<int>(nameof(Capacidad), ref fCapacidad, value); }
        }
        string fNoChasis;
        public string NoChasis
        {
            get { return fNoChasis; }
            set { SetPropertyValue<string>(nameof(NoChasis), ref fNoChasis, value); }
        }
        DateTime fVencimiento;
        public DateTime Vencimiento
        {
            get { return fVencimiento; }
            set { SetPropertyValue<DateTime>(nameof(Vencimiento), ref fVencimiento, value); }
        }
        double fKilometrajeCompra;
        public double KilometrajeCompra
        {
            get { return fKilometrajeCompra; }
            set { SetPropertyValue<double>(nameof(KilometrajeCompra), ref fKilometrajeCompra, value); }
        }
        double fKilometrajeActual;
        public double KilometrajeActual
        {
            get { return fKilometrajeActual; }
            set { SetPropertyValue<double>(nameof(KilometrajeActual), ref fKilometrajeActual, value); }
        }
        decimal fPrecioCompra;
        public decimal PrecioCompra
        {
            get { return fPrecioCompra; }
            set { SetPropertyValue<decimal>(nameof(PrecioCompra), ref fPrecioCompra, value); }
        }
        decimal fPrecioAlquiler;
        public decimal PrecioAlquiler
        {
            get { return fPrecioAlquiler; }
            set { SetPropertyValue<decimal>(nameof(PrecioAlquiler), ref fPrecioAlquiler, value); }
        }
        double fTasaInteres;
        public double TasaInteres
        {
            get { return fTasaInteres; }
            set { SetPropertyValue<double>(nameof(TasaInteres), ref fTasaInteres, value); }
        }
        decimal fDeducible;
        public decimal Deducible
        {
            get { return fDeducible; }
            set { SetPropertyValue<decimal>(nameof(Deducible), ref fDeducible, value); }
        }
        DateTime fFechaPago;
        public DateTime FechaPago
        {
            get { return fFechaPago; }
            set { SetPropertyValue<DateTime>(nameof(FechaPago), ref fFechaPago, value); }
        }
        string fCuotas;
        public string Cuotas
        {
            get { return fCuotas; }
            set { SetPropertyValue<string>(nameof(Cuotas), ref fCuotas, value); }
        }
        string fEnCalidadDe;
        public string EnCalidadDe
        {
            get { return fEnCalidadDe; }
            set { SetPropertyValue<string>(nameof(EnCalidadDe), ref fEnCalidadDe, value); }
        }
        string fPropiertario;
        public string Propiertario
        {
            get { return fPropiertario; }
            set { SetPropertyValue<string>(nameof(Propiertario), ref fPropiertario, value); }
        }
        string fImagenAuto;
        public string ImagenAuto
        {
            get { return fImagenAuto; }
            set { SetPropertyValue<string>(nameof(ImagenAuto), ref fImagenAuto, value); }
        }
        int fParqueo;
        public int Parqueo
        {
            get { return fParqueo; }
            set { SetPropertyValue<int>(nameof(Parqueo), ref fParqueo, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        DateTime fFechaDeRegistro;
        public DateTime FechaDeRegistro
        {
            get { return fFechaDeRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaDeRegistro), ref fFechaDeRegistro, value); }
        }
        int fEstado;
        public int Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<int>(nameof(Estado), ref fEstado, value); }
        }
        [Association(@"ReservacionVehiculoReferencesVehiculo")]
        public XPCollection<ReservacionVehiculo> ReservacionVehiculoes { get { return GetCollection<ReservacionVehiculo>(nameof(ReservacionVehiculoes)); } }
        [Association(@"TarifasVehiculoReferencesVehiculo")]
        public XPCollection<TarifasVehiculo> TarifasVehiculoes { get { return GetCollection<TarifasVehiculo>(nameof(TarifasVehiculoes)); } }
        [Association(@"VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollectionReferencesVehiculo")]
        public XPCollection<VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollection> VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollections { get { return GetCollection<VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollection>(nameof(VehiculoVehiculos_AccesorioVehiculoAccesorioVehiculoCollections)); } }
    }

}
